name: Sync Images
on:
  schedule:
    - cron: '0 0/2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install axios fs-extra
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run Downloader
        run: node fetch-images.js

      - name: Save Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "Image Bot"
          message: "Updated images from API"
          add: "images"
